name: google_tech_news
repository: https://github.com/hamas/Google-Tech-News

packages:
  - app
  - backend
  - core

command:
  bootstrap:
    # It seems you are using a newer version of Dart/Flutter where 'pub get' is standard.
    # Melos bootstrap links local packages.
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- "flutter analyze . || dart analyze ."
    description: Run analysis in all packages.

  test:
    run: melos exec --dir-exists="test" -- "flutter test || dart test"
    description: Run tests in all packages that have a test directory.

  clean:
    run: melos exec -- "flutter clean || rm -rf build"
    description: Clean all packages.
