name: google_tech_news
repository: https://github.com/hamas/Google-Tech-News

packages:
  - app
  - backend
  - core

command:
  bootstrap:
    # It seems you are using a newer version of Dart/Flutter where 'pub get' is standard.
    # Melos bootstrap links local packages.
    usePubspecOverrides: true

scripts:
  analyze:
    run: |
      melos run codegen
      melos exec -- "flutter analyze . || dart analyze ."
    description: Run analysis in all packages.

  codegen:
    run: |
      melos exec --dir-exists="lib" -- "dart run build_runner build --delete-conflicting-outputs"
      melos exec --dir-exists="l10n.yaml" -- "flutter gen-l10n"
    description: Run code generation (build_runner, l10n) in all packages.

  test:
    run: melos exec --dir-exists="test" -- "flutter test || dart test"
    description: Run tests in all packages that have a test directory.

  clean:
    run: melos exec -- "flutter clean || rm -rf build"
    description: Clean all packages.
