include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - prefer_relative_imports
    - unawaited_futures
    - unnecessary_lambdas
    - use_super_parameters
    - avoid_print
    - prefer_single_quotes

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
