arb-dir: lib/src/core/l10n
template-arb-file: app_en.arb
output-dir: lib/src/core/generated
synthetic-package: false
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: [en]
